Repository Dugout-programmers/Dugout, pull requests merged in 2025-02, with the labels that each got.

#257 [REFACTORE & FIX]
  src/api/supabase-api/userInfo.js
  src/components/PostHeader.vue
  src/components/common/Modal.vue
  src/components/mypage/ProfileViewAndEdit.test.vue
  src/components/ui/Footer.vue
  src/layouts/GameLayout.vue
  src/pages/Main.vue
  src/pages/QuizSelect.vue
  src/pages/TournamentSelect.vue
  src/stores/auth.js
Labels: 🔧 Fix

#288 [BUG] 로그인 오류 수정
  src/api/supabase-api/signIn.js
  src/router/index.js
  src/stores/auth.js
  src/stores/cheerSongStore.js
Labels: 🐛 Bug

#291 [FIX] 직관 크루 게시물 수정 오류 수정
  src/pages/CrewBoardEdit.vue
Labels: 🔧 Fix

#294 [BUG] 등록 버그 수정
  src/components/common/CreateHeader.vue
  src/pages/CrewBoardCreate.vue
  src/pages/FoodBoardCreate.vue
  src/pages/FreeBoardCreate.vue
  src/pages/PhotoBoardCreate.vue
Labels: 🐛 Bug

#299 [FEAT] 로딩창 수정
  src/components/common/CreateHeader.vue
  src/components/common/PostHeader.vue
  src/pages/CrewBoardDetail.vue
  src/pages/CrewBoardEdit.vue
  src/pages/FoodBoardDetail.vue
  src/pages/FreeBoardDetail.vue
  src/pages/FreeBoardEdit.vue
  src/pages/PhotoBoardCreate.vue
  src/pages/PhotoBoardDetail.vue
  src/pages/PhotoBoardEdit.vue
Labels: ✨ Feat

#302 [FEAT] 리다이렉트 추가
  public/_redirects
Labels: ✨ Feat

#306 [BUG] 새로고침 이슈
  public/_redirects
  src/router/index.js
Labels: 🐛 Bug

#309 [BUG] 소셜로그인 리다이렉트 추가
  src/api/supabase-api/signIn.js
Labels: 🐛 Bug

#311 [FIX] 야구 게임 토너먼트 게임 데이터 주소값 변경
  src/pages/TournamentHandsome.vue
  src/pages/TournamentHero.vue
  src/pages/TournamentTraitor.vue
Labels: 🔧 Fix

#313 [BUG] redirect 주소 수정
  src/api/supabase-api/signIn.js
Labels: 🐛 Bug

#314 [BUG] redirect 주소 수정
  src/api/supabase-api/signIn.js
Labels: 🐛 Bug

#315 [BUG] redirect url 수정
  src/api/supabase-api/signIn.js
Labels: 🐛 Bug

#316 [BUG] redirect url 수정
  src/api/supabase-api/signIn.js
Labels: 🐛 Bug

#317 [DELETE] 불필요한 파일 삭제
  .github/workflows/static.yml
  vite.config.js
Labels: 🐛 Bug

#318 [DELETE] 불필요한 코드 삭제
  src/router/index.js
Labels: 🐛 Bug

#319 [BUG] 배포 에러(리다이렉트)
  netlify.toml
  vite.config.js
Labels: 🐛 Bug

#322 [BUG] 뉴스데이터 proxy수정
  public/_redirects
  src/pages/News.vue
  vite.config.js
Labels: 🐛 Bug

#326 [FIX] 뉴스 api 수정
  src/pages/Highlight.vue
  src/pages/Main.vue
  src/pages/News.vue
Labels: 🔧 Fix

#328 [DESIGN] 레이아웃 수정
  src/pages/CrewBoard.vue
  src/pages/CrewBoardCreate.vue
  src/pages/CrewBoardDetail.vue
  src/pages/CrewBoardEdit.vue
  src/pages/FoodBoard.vue
  src/pages/FoodBoardCreate.vue
  src/pages/FoodBoardDetail.vue
  src/pages/FoodBoardEdit.vue
  src/pages/FreeBoardCreate.vue
  src/pages/FreeBoardDetail.vue
  src/pages/FreeBoardEdit.vue
  src/pages/PhotoBoard.vue
  src/pages/PhotoBoardCreate.vue
  src/pages/PhotoBoardDetail.vue
  src/pages/PhotoBoardEdit.vue
Labels: 🎨 Design

#329 [REFACTOR]게시판 기본프로필수정
  src/components/common/Commentbox.vue
  src/components/common/PostHeader.vue
  src/components/crewboard/CrewCard.vue
  src/components/foodboard/FoodBoardCard.vue
  src/components/photoboard/PhotoboardCard.vue
  src/pages/CrewBoardCreate.vue
  src/pages/CrewBoardEdit.vue
Labels: 🔧 Fix

#333 [BUG] 헤더 active 오류 수정
  src/components/ui/Header.vue
  src/pages/FreeBoardCreate.vue
Labels: 🐛 Bug
